### ISSUE TITLE
Cannot insert negative numbers into a `BIT(64)` column

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#10091]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
CREATE TABLE t(a BIT(64));
INSERT INTO t VALUES (-1);
SELECT hex(a) FROM t;
```

2. What did you expect to see?

On MySQL 5.7 and 8.0:

```
mysql> CREATE TABLE t(a BIT(64));
Query OK, 0 rows affected (0.04 sec)

mysql> INSERT INTO t VALUES (-1);
Query OK, 1 row affected (0.01 sec)

mysql> SELECT hex(a) FROM t;
+------------------+
| hex(a)           |
+------------------+
| FFFFFFFFFFFFFFFF |
+------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

On TiDB, it reports that the negative number is out-of-range.

```
mysql> CREATE TABLE t(a BIT(64));
Query OK, 0 rows affected (0.05 sec)

mysql> INSERT INTO t VALUES (-1);
ERROR 1264 (22003): Out of range value for column 'a' at row 1
mysql> SELECT hex(a) FROM t;
Empty set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```yaml
Release Version: v3.0.0-beta.1-87-gf723f0b14
Git Commit Hash: f723f0b14317ad8cc6d7f8106eb93ab233624642
Git Branch: master
UTC Build Time: 2019-04-09 07:23:07
GoVersion: go version go1.12.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```
## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123
