### ISSUE TITLE
When specifying Collation for a Column, the corresponding Charset should be set as well

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#10122]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
create table test.t(a varchar(10) collate ascii_bin);
```
2. What did you expect to see?
```
mysql> select * from information_schema.columns where table_name='t' and table_schema='test'\G
*************************** 1. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: t
             COLUMN_NAME: a
        ORDINAL_POSITION: 1
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: varchar
CHARACTER_MAXIMUM_LENGTH: 10
  CHARACTER_OCTET_LENGTH: 10
       NUMERIC_PRECISION: NULL
           NUMERIC_SCALE: NULL
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: ascii
          COLLATION_NAME: ascii_bin
             COLUMN_TYPE: varchar(10)
              COLUMN_KEY: 
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
1 row in set (0.00 sec)
```

3. What did you see instead?
```
mysql> select * from information_schema.columns where table_name='t' and table_schema='test'\G
*************************** 1. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: t
             COLUMN_NAME: a
        ORDINAL_POSITION: 1
          COLUMN_DEFAULT: NULL
             IS_NULLABLE: YES
               DATA_TYPE: varchar
CHARACTER_MAXIMUM_LENGTH: 10
  CHARACTER_OCTET_LENGTH: 10
       NUMERIC_PRECISION: NULL
           NUMERIC_SCALE: NULL
      DATETIME_PRECISION: NULL
      CHARACTER_SET_NAME: utf8mb4
          COLLATION_NAME: utf8mb4_bin
             COLUMN_TYPE: varchar(10)
              COLUMN_KEY: 
                   EXTRA: 
              PRIVILEGES: select,insert,update,references
          COLUMN_COMMENT: 
   GENERATION_EXPRESSION: 
1 row in set (0.03 sec)
```
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
mysql> select version();
+-----------------------------------------+
| version()                               |
+-----------------------------------------+
| 5.7.25-TiDB-v3.0.0-beta.1-94-g5a34c4b9d |
+-----------------------------------------+
1 row in set (0.00 sec)
```
