### ISSUE TITLE
upgrade from 2.1.14 to 3.0.0 ,tidb startup fail

### ISSUE THREAD

**Issue by wonderful1984** [pingcap/tidb#11261]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
upgrade from 2.1.14 to 3.0.0

~]$ tidb3/bin/tidb-server --config-check /apps/conf/tidb/tidb10080.toml
config check successful

~]$ tidb3/bin/tidb-server --config /apps/conf/tidb/tidb10080.toml      
FATA[0000] toml: cannot load TOML value of type int64 into a Go string

**Comment by wonderful1984** [comment]
[tidb10080.txt](https://github.com/pingcap/tidb/files/3392400/tidb10080.txt)

**Comment by lonng** [comment]
@wonderful1984 Seems the configuration item type does not match.

**Comment by lonng** [comment]
@wonderful1984 The `pessimistic-txn.ttl` should be a string.
```toml
[pessimistic-txn]
# enable pessimistic transaction.
enable = false

# start pessimistic transaction by default.
default = false

# max retry count for a statement in a pessimistic transaction.
max-retry-count = 256

# default TTL in milliseconds for pessimistic lock.
ttl = "60000"
```
