### ISSUE TITLE
invalid marker byte, group bytes "\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x1e\\x00"

### ISSUE THREAD

**Issue by H-ZeX** [pingcap/tidb#13061]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
use this tidb https://github.com/pingcap/tidb/pull/12858/commits/f4fd9894eced4dad22c95552aea4884c5e9b4a7d and this tikv (https://github.com/tikv/tikv/commit/50139edd79ac60bd9ee95f1630b227d76c5a26b5).
The pd is 
```
$ ~/program/goland/pd/bin/pd-server -V                                           
Release Version: v4.0.0-alpha-87-gf1f4553f
Git Commit Hash: f1f4553f2d770db4d59c50e2adf9f2cc2e035d59
Git Branch: HEAD
UTC Build Time:  2019-10-21 03:37:24

```
And use this config

```toml
name = "pd"
data-dir = "/tmp/copr_test/pd_with_batch"
client-urls = "http://127.0.0.1:4479"
peer-urls = "http://127.0.0.1:4480"
```
```toml
port = 4007
store = "tikv"
path = "127.0.0.1:4479"

[status]
report-status = false
```
```toml
[server]
end-point-enable-batch-if-possible = true
## Listening address.
addr = "127.0.0.1:20162"
status-addr = ""

[pd]
endpoints = ["127.0.0.1:4479"]

[storage]
data-dir = "/tmp/copr_test/tikv_with_batch"

[rocksdb]
max-open-files = 64

[raftdb]
max-open-files = 64
```
The TiDB should ` make failpoint-enable` and set env var `export GO_FAILPOINTS="github.com/pingcap/tidb/expression/PushDownTestSwitcher=return(\"all\")"` 
The run this sql 
```sql
use test;
create table tb9
(
    a bigint
);
insert into tb9 (a)
values (30);

select *
from tb9;
```
will get this error `(1105, 'invalid marker byte, group bytes "\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x1e\\x00"')`

Although merge master will success run this sql, but I think this err should not be ignore.
