### ISSUE TITLE
'invalid marker byte, group bytes "\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\n\\x00"'

### ISSUE THREAD

**Issue by H-ZeX** [pingcap/tidb#13086]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
- TiDB
   tidb before this commit b80b417803d42734126a3764e642331ab5a40991, such as 7bfa8967e174642e270677e1348781a7c0e8dad2, e8294ad636abe63094a993ed27ccbef7d29abb52
- TiKV
    ```
   $ ~/Downloads/tikv-ups/bin/tikv-server -V                                                                                                
   TiKV 
   Release Version:   4.0.0-alpha
   Git Commit Hash:   109624cf112cfd8bb7eb4b6e57ae9768911c228d
   Git Commit Branch: master
   UTC Build Time:    2019-10-31 06:16:31
   Rust Version:      rustc 1.39.0-nightly (c6e9c76c5 2019-09-04)
   ```
- PD
   ```
   $ ~/program/goland/pd/bin/pd-server -V
   Release Version: v4.0.0-alpha-87-gf1f4553f
   Git Commit Hash: f1f4553f2d770db4d59c50e2adf9f2cc2e035d59
   Git Branch: HEAD
   UTC Build Time:  2019-10-21 03:37:24
   ```
And use this config

```toml
name = "pd"
data-dir = "/tmp/copr_test/pd_with_batch"
client-urls = "http://127.0.0.1:4479"
peer-urls = "http://127.0.0.1:4480"
```
```toml
port = 4007
store = "tikv"
path = "127.0.0.1:4479"

[status]
report-status = false
```
```toml
[server]
end-point-enable-batch-if-possible = true
## Listening address.
addr = "127.0.0.1:20162"
status-addr = ""

[pd]
endpoints = ["127.0.0.1:4479"]

[storage]
data-dir = "/tmp/copr_test/tikv_with_batch"

[rocksdb]
max-open-files = 64

[raftdb]
max-open-files = 64
```
The run this sql 
```sql
DROP table if exists tmp2;
create table tmp2
(
    a int
);
insert tmp2
values (10);
select *
from tmp2;
```
will get this error `(1105, 'invalid marker byte, group bytes "\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\n\\x00"')`.

**This problem is not detected by CI.**

**I think it is necessay to add such test like the step above to detect such problem.**
