### ISSUE TITLE
statements_summary query_sample_text shows prepared statement form

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#16653]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

I ran tpcc against master, and then observed the workload in `information_schema.statements_summary`.

### 2. What did you expect to see?

I was really hoping to see `query_sample_text` so that I could take the query and run it through explain. Instead it showed only the prepared statement form - which is non-explainable.

### 3. What did you see instead?

```
mysql> select * from statements_summary where stmt_type='select' order by sum_latency desc limit 2\G
*************************** 1. row ***************************
       SUMMARY_BEGIN_TIME: 2020-04-20 20:30:00
         SUMMARY_END_TIME: 2020-04-20 21:00:00
                STMT_TYPE: select
              SCHEMA_NAME: tpcc
                   DIGEST: 79cdf6c3eccead898330bda0b5630d505010bed8dac509c9d1a4e485e9e29b60
              DIGEST_TEXT: select c_discount , c_last , c_credit , w_tax from customer , warehouse where w_id = ? and c_w_id = w_id and c_d_id = ? and c_id = ?
              TABLE_NAMES: tpcc.customer,tpcc.warehouse
              INDEX_NAMES: NULL
              SAMPLE_USER: root
               EXEC_COUNT: 16146
               SUM_ERRORS: 0
             SUM_WARNINGS: 0
              SUM_LATENCY: 36927867322
              MAX_LATENCY: 104421632
              MIN_LATENCY: 471610
              AVG_LATENCY: 2287121
        AVG_PARSE_LATENCY: 9622
        MAX_PARSE_LATENCY: 4654548
      AVG_COMPILE_LATENCY: 318677
      MAX_COMPILE_LATENCY: 5278069
         SUM_COP_TASK_NUM: 0
     MAX_COP_PROCESS_TIME: 0
  MAX_COP_PROCESS_ADDRESS: NULL
        MAX_COP_WAIT_TIME: 0
     MAX_COP_WAIT_ADDRESS: NULL
         AVG_PROCESS_TIME: 0
         MAX_PROCESS_TIME: 0
            AVG_WAIT_TIME: 0
            MAX_WAIT_TIME: 0
         AVG_BACKOFF_TIME: 0
         MAX_BACKOFF_TIME: 0
           AVG_TOTAL_KEYS: 0
           MAX_TOTAL_KEYS: 0
       AVG_PROCESSED_KEYS: 0
       MAX_PROCESSED_KEYS: 0
        AVG_PREWRITE_TIME: 0
        MAX_PREWRITE_TIME: 0
          AVG_COMMIT_TIME: 0
          MAX_COMMIT_TIME: 0
   AVG_GET_COMMIT_TS_TIME: 0
   MAX_GET_COMMIT_TS_TIME: 0
  AVG_COMMIT_BACKOFF_TIME: 0
  MAX_COMMIT_BACKOFF_TIME: 0
    AVG_RESOLVE_LOCK_TIME: 0
    MAX_RESOLVE_LOCK_TIME: 0
AVG_LOCAL_LATCH_WAIT_TIME: 0
MAX_LOCAL_LATCH_WAIT_TIME: 0
           AVG_WRITE_KEYS: 0
           MAX_WRITE_KEYS: 0
           AVG_WRITE_SIZE: 0
           MAX_WRITE_SIZE: 0
     AVG_PREWRITE_REGIONS: 0
     MAX_PREWRITE_REGIONS: 0
            AVG_TXN_RETRY: 0
            MAX_TXN_RETRY: 0
        SUM_BACKOFF_TIMES: 0
            BACKOFF_TYPES: NULL
                  AVG_MEM: 53512
                  MAX_MEM: 53512
        AVG_AFFECTED_ROWS: 0
               FIRST_SEEN: 2020-04-20 20:49:34
                LAST_SEEN: 2020-04-20 20:51:25
        QUERY_SAMPLE_TEXT: SELECT c_discount, c_last, c_credit, w_tax FROM customer, warehouse WHERE w_id = ? AND c_w_id = w_id AND c_d_id = ? AND c_id = ?
         PREV_SAMPLE_TEXT: 
              PLAN_DIGEST: d40707dd740e8032fe6a362a242c86f5bb6409008ae3e968c45833be2f8e3065
                     PLAN: 	Projection_7    	root	0.9999999999999999	tpcc.customer.c_discount, tpcc.customer.c_last, tpcc.customer.c_credit, tpcc.warehouse.w_tax
	└─HashJoin_8    	root	0.9999999999999999	CARTESIAN inner join
	  ├─Point_Get_10	root	1                 	table:customer, index:PRIMARY(c_w_id, c_d_id, c_id)
	  └─Point_Get_11	root	1                 	table:warehouse, handle:10

```

See the `?` for values under `query_sample_text`. In MySQL the query sample shows something that is directly explainable. The digest_text shows the prepared statement form.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-302-g8c455e86c
Git Commit Hash: 8c455e86c136ac020129998c94f890448367f62a
Git Branch: master
UTC Build Time: 2020-04-21 02:25:12
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```
