### ISSUE TITLE
Scenario orientation data migration service instead of combining a bundle of tools

### ISSUE THREAD

**Issue by lonng** [pingcap/tidb#17615]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Provide a scenario orientation data migration service instead of providing a bundle of tools. The data migration service should be an integrated product and the users do not need to learn various usage of different tools. 

I must learn how to use TiDB-Lightning and how to deploy a multiple instances TiDB-Lightning cluster if I want to import some CSV files on multiple hosts. But the ideal way should like the following (the users describe what they want and the `Data Migration Service` auto-generate properly deployment):

- Import CSV from multiple hosts (the low-level implementation should use multiple TiDB-Lightning instances but the detail is transparent to users)

    ```yaml
    type: csv
    source:
      - host: 123.2.3.4
        path: /path/to/csv
      - host: 123.2.3.5
        path: /path/to/csv
    sink:
      - host: 123.2.3.5
        port: 4000
    ```

- Migrate data from multiple MySQL instances

   ```yaml
    type: mysql
    source:
      - host: 123.2.3.4
        port: 3306
      - host: 123.2.3.5
        port: 3306
    sink:
      - host: 123.2.3.9
        port: 4000
    workers:
      - host: 123.2.3.5
      - host: 123.2.3.6
      - host: 123.2.3.7
      - host: 123.2.3.8
   ```

- and so on.
