### ISSUE TITLE
caused by: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

### ISSUE THREAD

**Issue by Donaldhan** [pingcap/tidb#19247]
OS ： ubuntu16.04；
install tidb cluster base on this guide（https://docs.pingcap.com/zh/tidb/stable/quick-start-with-tidb， 使用 TiUP cluster 在单机上模拟生产环境部署步骤）
when i install cluster get following error：

```
Error: Failed to initialize TiDB environment on remote host '192.168.230.130' (task.env_init.failed)
  caused by: Failed to create new system user 'tidb' on remote host
    caused by: Failed to execute command over SSH for 'root@192.168.230.130:22'
      caused by: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain

```

firstly, root can ssh use no password, such as
```
ssh root@192.168.230.130
```

but i doubt why throw this error:
```
caused by: Failed to execute command over SSH for 'root@192.168.230.130:22'
```

Is ssh port error, or should't use the port?????

my tidb cofing

```yaml
# # Global variables are applied to all deployments and used as the default value of
# # the deployments if a specific deployment value is missing.
global:
 user: "tidb"
 ssh_port: 22
 deploy_dir: "/tidb-deploy"
 data_dir: "/tidb-data"

# # Monitored variables are applied to all the machines.
monitored:
 node_exporter_port: 9100
 blackbox_exporter_port: 9115

server_configs:
 tidb:
   log.slow-threshold: 300
 tikv:
   readpool.storage.use-unified-pool: false
   readpool.coprocessor.use-unified-pool: true
 pd:
   replication.enable-placement-rules: true
 tiflash:
   logger.level: "info"

pd_servers:
 - host: 192.168.230.130

tidb_servers:
 - host: 192.168.230.130

tikv_servers:
 - host: 192.168.230.130
   port: 20160
   status_port: 20180

 - host: 192.168.230.130
   port: 20161
   status_port: 20181

 - host: 192.168.230.130
   port: 20162
   status_port: 20182

tiflash_servers:
 - host: 192.168.230.130

monitoring_servers:
 - host: 192.168.230.130

grafana_servers:
 - host: 192.168.230.130
````
