### ISSUE TITLE
2-node tikv deployment, single node load is too high

### ISSUE THREAD

**Issue by AntiKnot** [pingcap/tidb#19686]
## Performance Questions

- What version of TiDB are you using?

tidb v4.0.0-beta.2-1006-g6831e487a
tipd v4.0.0-rc.2-164-g7a6a9daa
tikv v4.1.0-alpha

- What's the observed and your expected performance respectively?
It is expected that the two tikv nodes can achieve load balance in the read and write tasks, or finally achieve balance after a period of time.
But in the chart of ppref and grafna. Tikv-node1 is always about twice the load of tikv-nodo2.

- Deployment environment
ECS: aliyunECS ecs.c6e.xlarge centos7.8 4*cpu 8*mem ESSD PL0 40GiB(2280 IOPS)
same ECS*5

- Topo
**DB+DB+(KV+PD)+(KV+PD)+(DeployCommandNode+Monitor)**
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

monitored:
  node_exporter_port: 9100
  blackbox_exporter_port: 9115

server_configs:
  tidb:
    log.slow-threshold: 300
    binlog.enable: false
    binlog.ignore-error: false
  tikv:
    server.grpc-concurrency: 4
    raftstore.apply-pool-size: 2
    raftstore.store-pool-size: 2
    rocksdb.max-sub-compactions: 1
    storage.block-cache.capacity: "4GB"
    readpool.unified.max-thread-count: 12
    readpool.storage.use-unified-pool: false
    readpool.coprocessor.use-unified-pool: true
  pd:
    schedule.leader-schedule-limit: 4
    schedule.region-schedule-limit: 2048
    schedule.replica-schedule-limit: 64

pd_servers:
  - host: xxx.xxx.xxx.xx8
  - host: xxx.xxx.xxx.xx0

tidb_servers:
  - host: xxx.xxx.xxx.xx9
  - host: xxx.xxx.xxx.xx7

tikv_servers:
  - host: xxx.xxx.xxx.xx0
  - host: xxx.xxx.xxx.xx8

monitoring_servers:
  - host: xxx.xxx.xxx.xx6

grafana_servers:
  - host: xxx.xx.xxx.xx6

alertmanager_servers:
  - host: xxx.xxx.xxx.xx6
```

use sysbench test benchmark cpu,io,mem.  
In the prepare phase and run phase

- sysbench config
```
mysql-user=root
mysql-password=
mysql-port=4000
mysql-host=172.27.133.127
mysql-db=sbtest
time=120
threads=128
report-interval=5
verbosity=5
validate
db-driver=mysql
percentile=99
```

- sysbench test
sysbench --config-file=sbtest_config oltp_read_write --tables=8 --table-size=1000000 
sysbench --config-file=sbtest_config oltp_read_write --tables=32 --table-size=1000000 
sysbench --config-file=sbtest_config oltp_read_write --tables=1 --table-size=10000000 

![image](https://user-images.githubusercontent.com/14977542/91872291-4980e180-ecaa-11ea-868f-d20af8ba282e.png)
![image](https://user-images.githubusercontent.com/14977542/91872319-4f76c280-ecaa-11ea-8cc4-4e819cfd3767.png)
![image](https://user-images.githubusercontent.com/14977542/91872346-5ac9ee00-ecaa-11ea-9abc-5b9dcd8a0229.png)
![image](https://user-images.githubusercontent.com/14977542/91872372-60bfcf00-ecaa-11ea-8ae1-b22caaa41058.png)
