### ISSUE TITLE
add runbook_url for TiDB alerts

### ISSUE THREAD

**Issue by zjj2wry** [pingcap/tidb#19840]
## Feature Request

**Is your feature request related to a problem? Please describe:**

```
  - alert: TiDB_schema_error
    expr: increase(tidb_session_schema_lease_error_total{type="outdated"}[15m]) > 0
    for: 1m
    labels:
      env: ENV_LABELS_ENV
      level: emergency
      expr:  increase(tidb_session_schema_lease_error_total{type="outdated"}[15m]) > 0
    annotations:
      description: 'cluster: ENV_LABELS_ENV, instance: {{ $labels.instance }}, values:{{ $value }}'
      value: '{{ $value }}'
      summary: TiDB schema error
+     runbook_url: https://docs.pingcap.com/tidb/stable/alert-rules#tidb_schema_error
```
There is some alert solution(https://docs.pingcap.com/tidb/stable/alert-rules#tidb_schema_error) on TiDB official website, I hope we can add it to runbook_url annotations. Then users can be got the URL by '{{ (index .Alerts 0).Annotations.runbook_url }}' templates.  The following is the alerts of k8s

![image](https://user-images.githubusercontent.com/18045633/92365851-f9c96c80-f126-11ea-89a2-23c32d922249.png)

FYI: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/runbook.md#alert-name-cputhrottlinghigh

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
