### ISSUE TITLE
Can i insert data larger than 6mb into the column(TIDB)? 

### ISSUE THREAD

**Issue by KwonMinho** [pingcap/tidb#21276]
If possible, what can be modified in tidb configuration?  🤔

**Comment by sev7ndayyoo** [comment]
This limit cannot currently be modified through configuration.

**Comment by ljluestc** [comment]
```

server_configs:
  tidb-server:
    log.level: "info"  # Adjust log level as needed (e.g., debug for debugging)
    performance.feedback-probability: 0.05  # Enable performance feedback to optimize execution plans
    binlog.enable: false  # Disable binlog if not needed
    tikv-client.grpc-connection-count: 10  # Increase the number of gRPC connections to TiKV for parallelism
```
