### ISSUE TITLE
Get Incorrect limit_in_bytes and usage_in_bytes

### ISSUE THREAD

**Issue by mahjonp** [pingcap/tidb#22132]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

TiDB parses "/sys/fs/cgroup/memory/memory.limit_in_bytes" to get memory limit value and "/sys/fs/cgroup/memory/memory.usage_in_bytes" to retrieve usage currently, it's not correct in some situations.

### 1. Minimal reproduce step (Required)

For example, I deploy a tidb cluster through TiUP like following steps:

1. Edit topology.yaml

```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/data1/tidb/deploy"
  data_dir: "/data1/tidb/deploy/data"
  resource_control:
    memory_limit: "4G"
    cpu_quota: "200%"

tidb_servers:
  - host: 172.16.5.86

tikv_servers:
  - host: 172.16.5.86

pd_servers:
  - host: 172.16.5.86
```

2. tiup cluster deploy test-tidb nightly topology.yaml
3. tiup cluster start test-tidb

### 2. What did you expect to see? (Required)

TiDB-server should get memory limit and usage in `/sys/fs/cgroup/memory/system.slice/tidb-4000.service/memory.limit_in_bytes` and `cat /sys/fs/cgroup/memory/system.slice/tidb-4000.service/memory.usage_in_bytes`

### 3. What did you see instead (Required)

https://github.com/wshwsh12/tidb/blob/e9896cf8ae6c11e58f15fabe6802283dfd20585e/util/memory/meminfo.go#L43-L44

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1941-gdad3b5e87
Edition: Community
Git Commit Hash: dad3b5e87d21caf29bd7f0c7d968cd410e7a5cdd
Git Branch: master
UTC Build Time: 2020-12-30 14:16:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

```
