### ISSUE TITLE
tiup cluster deploy example 4.0.0 ./topo.yaml --user root -p    Failed

### ISSUE THREAD

**Issue by assmdx** [pingcap/tidb#23126]
OS: CentOs 7.9

topo.yml:

```
# # Global variables are applied to all deployments and used as the default value of
# # the deployments if a specific deployment value is missing.
global:
 user: "tidb"
 ssh_port: 22
 deploy_dir: "/tidb-deploy"
 data_dir: "/tidb-data"

# # Monitored variables are applied to all the machines.
monitored:
 node_exporter_port: 9100
 blackbox_exporter_port: 9115

server_configs:
 tidb:
   log.slow-threshold: 300
 tikv:
   readpool.storage.use-unified-pool: false
   readpool.coprocessor.use-unified-pool: true
 pd:
   replication.enable-placement-rules: true
   replication.location-labels: ["host"]
 tiflash:
   logger.level: "info"

pd_servers:
 - host: 192.168.0.10

tidb_servers:
 - host: 192.168.0.10

tikv_servers:
 - host: 192.168.0.10
   port: 20160
   status_port: 20180
   config:
     server.labels: { host: "logic-host-1" }

 - host: 192.168.0.10
   port: 20161
   status_port: 20181
   config:
     server.labels: { host: "logic-host-2" }

 - host: 192.168.0.10
   port: 20162
   status_port: 20182
   config:
     server.labels: { host: "logic-host-3" }

tiflash_servers:
 - host: 192.168.0.10

monitoring_servers:
 - host: 192.168.0.10

grafana_servers:
 - host: 192.168.0.10
```

run command: 
```
tiup cluster deploy example 4.0.0 ./topo.yaml --user root -p
```

got:
![image](https://user-images.githubusercontent.com/19722693/110050776-9a73ae80-7d8f-11eb-914a-f0162cf04cdf.png)
