### ISSUE TITLE
How to update pd member peer url of running cluster

### ISSUE THREAD

**Issue by truong-hua** [pingcap/tidb#25050]
Etcd has a command `etcdctl member update <member_id> --peer-urls=<new_peer_url>` to cover a case that a etcd member is restarted and it's IP address has been changed.

I have a 3 node pd cluster as follows:
```
version: '2.1'

services:
  pd0:
    image: pingcap/pd:latest
    volumes:
      - data0:/data
    command:
      - --name=pd3
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data
  pd1:
    image: pingcap/pd:latest
    volumes:
      - data1:/data
    command:
      - --name=pd1
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd1:2379
      - --advertise-peer-urls=http://pd1:2380
      - --initial-cluster=pd0=http://pd0:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data
  pd2:
    image: pingcap/pd:latest
    volumes:
      - data2:/data
    command:
      - --name=pd2
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd2:2379
      - --advertise-peer-urls=http://pd2:2380
      - --initial-cluster=pd0=http://pd0:2380,pd1=http://pd1:2380,pd2=http://pd2:2380
      - --data-dir=/data

volumes:
  data0:
  data1:
  data2:
```

Now I shutdown pd0, I keep all volumes persistent and replace pd0 with a new pd4 as follows:
```
version: '2.1'

services:
  pd4:
    image: pingcap/pd:latest
    volumes:
      - data0:/data
    command:
      - --name=pd4
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd4:2379
      - --advertise-peer-urls=http://pd4:2380
      - --join=http://pd1:2380
      - --data-dir=/data
volumes:
  data0:
```

After pd4 has been started, it joined to the cluster successfully and every is seem worked. But when I do `/pd-ctl member` on a node, it gives me:
```
{
  "header": {
    "cluster_id": 6969063719555665170
  },
  "members": [
    {
      "name": "pd2",
      "member_id": 3486081234046183923,
      "peer_urls": [
        "http://pd2:2380"
      ],
      "client_urls": [
        "http://pd2:2379"
      ],
      "deploy_path": "/",
      "binary_version": "v5.0.1",
      "git_hash": "ea1449c7c693d94661b3c60d35b8679ebfb3da34"
    },
    {
      "name": "pd4",
      "member_id": 16382016976602811638,
      "peer_urls": [
        "http://pd0:2380"
      ],
      "client_urls": [
        "http://pd4:2379"
      ],
      "deploy_path": "/",
      "binary_version": "v5.0.1",
      "git_hash": "ea1449c7c693d94661b3c60d35b8679ebfb3da34"
    },
    {
      "name": "pd1",
      "member_id": 17107318113395953248,
      "peer_urls": [
        "http://pd1:2380"
      ],
      "client_urls": [
        "http://pd1:2379"
      ],
      "deploy_path": "/",
      "binary_version": "v5.0.1",
      "git_hash": "ea1449c7c693d94661b3c60d35b8679ebfb3da34"
    }
  ],
  "leader": {
    "name": "pd1",
    "member_id": 17107318113395953248,
    "peer_urls": [
      "http://pd1:2380"
    ],
    "client_urls": [
      "http://pd1:2379"
    ],
    "deploy_path": "/",
    "binary_version": "v5.0.1",
    "git_hash": "ea1449c7c693d94661b3c60d35b8679ebfb3da34"
  },
  "etcd_leader": {
    "name": "pd1",
    "member_id": 17107318113395953248,
    "peer_urls": [
      "http://pd1:2380"
    ],
    "client_urls": [
      "http://pd1:2379"
    ],
    "deploy_path": "/",
    "binary_version": "v5.0.1",
    "git_hash": "ea1449c7c693d94661b3c60d35b8679ebfb3da34"
  }
}
```

And you see, the pd4 peer url is still remain "http://pd0:2380" which is of the old pd0. How can I update that peer url to reflect a new address? In reality, I use Docker Swarm and I use IP address for peer urls and every time the container restarted, I have to update the peer urls config to a new IP address.
