### ISSUE TITLE
TiDB v5.1.0 consumes more CPU than v5.0.2 in ycsb workload-e

### ISSUE THREAD

**Issue by youjiali1995** [pingcap/tidb#25726]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Topo:
```
          spec:
            machines:
              - name: m1
                exclusive: true
            items:
              - name: tidb
                spec:
                  memory: 32GB
                  cores: 16
                  machine: m1
              - name: pd
                spec:
                  memory: 8GB
                  cores: 2
                  machine: m1
              - name: tikv-1
                spec:
                  memory: 64GB
                  cores: 16
                  disks:
                    disk1:
                      kind: nvme
                      mountPath: /disk1
                  machine: m1
              - name: workload
                spec:
                  memory: 8GB
                  cores: 4
                  machine: m1
```

ycsb workload-e:
```
                      echo "recordcount=100000000" >> global.conf
                      echo "operationcount=10000000" >> global.conf
                      echo "workload=core" >> global.conf
                      echo "fieldcount=10" >> global.conf
                      echo "fieldlength=100" >> global.conf
                      echo "threadcount=500" >> global.conf
                      echo "requestdistribution=zipfian" >> global.conf
                      go-ycsb run mysql \
                          -P /ycsb/workloads/{{workflow.parameters.workload}} \
                          -P global.conf \
                          -p mysql.host=$tidb \
                          -p mysql.port=4000
```

### 2. What did you expect to see? (Required)

Same throughput and CPU usage.

### 3. What did you see instead (Required)

The throughput is the same(?) in the two versions but CPU usage is different.

v5.1
![image](https://user-images.githubusercontent.com/14819777/123196445-85f12880-d4dc-11eb-9688-4ecc1ef3e4bb.png)

v5.0.2
![image](https://user-images.githubusercontent.com/14819777/123196478-96090800-d4dc-11eb-981a-60e56a8d4242.png)

### 4. What is your TiDB version? (Required)

v5.1.0 go1.16.4
v5.0.2 go1.13
