### ISSUE TITLE
field max-days not found in type spec.TiDBSpec

### ISSUE THREAD

**Issue by cgaofeng** [pingcap/tidb#27365]
tidb_servers:
- host: 192.168.24.101
  ssh_port: 22
  port: 4000
  status_port: 10080
  deploy_dir: /data1/tidb-deploy/tidb-4000
  log_dir: /data1/tidb-deploy/tidb-4000/log
  max-days:  1
  max-backups: 1
  arch: amd64
  os: linux

**Comment by ljluestc** [comment]
To resolve this issue, you should update the configuration file to use the correct configuration options:
```
tidb_servers:
  - host: 192.168.24.101
    ssh_port: 22
    port: 4000
    status_port: 10080
    deploy_dir: /data1/tidb-deploy/tidb-4000
    log_dir: /data1/tidb-deploy/tidb-4000/log
    max-keep-duration: 1d
    max-backups: 1
    arch: amd64
    os: linux

```
