### ISSUE TITLE
Configuration guidance for docker/k8s and servers with small amount of resource

### ISSUE THREAD

**Issue by xpepermint** [pingcap/tidb#27840]
Ref: https://github.com/tikv/tikv/issues/10908

There's a lot of configuration keys that we can twist but it looks like nothing works for a very small server setup. In k8s you have to accurately predict the CPU and RAM usage to prevent pods to go down (usually because of OOM). This seems very difficult with `TiDB/TiKV` and memory is growing indefinitely.

Could someone please post recommendations on how to keep the resource low? I'd like to be able to run TiDB (TiKV) in a pod with let say 512MB RAM and 0.1 CPU. What configuration would work? What parameters I should set and how?

**Comment by ljluestc** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tidb-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: tidb-container
        image: pingcap/tidb:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.1"
          requests:
            memory: "512Mi"
            cpu: "0.1"

```
