### ISSUE TITLE
Very slow performance when adding indexes and columns

### ISSUE THREAD

**Issue by rsaphala** [pingcap/tidb#30411]
I’m experiencing very slow performance when adding index and column to a table. Could anyone help? This table has 30 million rows only
```

create table sbtest2
(
    id  int auto_increment
        primary key,
    k   int       default 0  not null,
    c   char(120) default '' not null,
    pad char(60)  default '' not null
);
```
```

alter table sbtest2 add column aaa int (25 minutes and still not finished)

alter table sbtest2 add index (c) (40 minutes and still not finished)
```

This is my cluster spec:

```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
spec:
  version: v5.2.1
  timezone: UTC
  configUpdateStrategy: RollingUpdate
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  schedulerName: tidb-scheduler
  pd:
    baseImage: pingcap/pd
    replicas: 1
    requests:
      storage: "100Gi"
      cpu: "3"
      memory: "10Gi"
    config:
      log:
        level: info
      replication:
        location-labels:
        - zone
        max-replicas: 1
    nodeSelector:
      dedicated: pd
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: pd
  tikv:
    baseImage: pingcap/tikv
    replicas: 3
    storageClassName: "ssd"
    requests:
      storage: "500Gi"
      cpu: "6"
      memory: 24Gi
    annotations:
      tidb.pingcap.com/sysctl-init: "true"
    podSecurityContext:
      sysctls:
      - name: net.core.somaxconn
        value: "32768"
    config: {}
    nodeSelector:
      dedicated: tikv
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: tikv
  tidb:
    baseImage: pingcap/tidb
    replicas: 2
    requests:
      cpu: 6
      memory: 24Gi
    storageClassName: "ssd"
    service:
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
      exposeStatus: true
      externalTrafficPolicy: Local
      type: LoadBalancer
    config:
      log:
        level: info
      performance:
        max-procs: 0
        tcp-keep-alive: true
    annotations:
      tidb.pingcap.com/sysctl-init: "true"
    podSecurityContext:
      sysctls:
      - name: net.ipv4.tcp_keepalive_time
        value: "300"
      - name: net.ipv4.tcp_keepalive_intvl
        value: "75"
      - name: net.core.somaxconn
        value: "32768"
    separateSlowLog: true
    nodeSelector:
      dedicated: tidb
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: tidb


```

The above cluster runs on GKE with N2 Node type

Cluster metrics:
https://snapshot.raintank.io/dashboard/snapshot/cGKaqDChkD5bDs6AQ8Sx6AwUtIf0MYnB?orgId=2
