### ISSUE TITLE
Lightning: import to wrong db name with some route rules

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tidb#33381]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

test file and config to reproduce this is here :[test-lighning-route.zip](https://github.com/pingcap/tidb/files/8338860/test-lighning-route.zip)

dumped data from dumping

```bash
├── dumped_data
│   ├── metadata
│   ├── webui-schema-create.sql
│   └── webui.t1-schema.sql
├── tidb-lightning.log
└── webui.toml
```

task.toml
```toml
[lightning]
file = "tidb-lightning.log"
level = "info"

[tikv-importer]
backend = "tidb"

[mydumper]
data-source-dir = "./dumped_data"

[tidb]
host = "127.0.0.1"
password = "123456"
port = 3307
user = "root"

[[routes]]
schema-pattern = "webui"
target-schema = "webui_test"

```

### 2. What did you expect to see? (Required)

i want to route db: `webui` to `webui_test` and keep table names 

### 3. What did you see instead (Required)

lightning two db  webui and webui_test 

```bash
MySQL root@127.0.0.1:(none)> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| dm_meta            |
| mysql              |
| performance_schema |
| sys                |
| webui              |
| webui_test         |
+--------------------+
```

### 4. What is your TiDB version? (Required)

```
❯ tidb-lightning -V
Release Version: v6.1.0-alpha-38-g6d0185585-dirty
Git Commit Hash: 6d01855856aac61e0829f73ed8a47be6add45321
Git Branch: master
Go Version: go1.18
UTC Build Time: 2022-03-24 05:41:35
Race Enabled: false
```
