### ISSUE TITLE
Does Prometheus monitoring need to do client certificate validation?

### ISSUE THREAD

**Issue by callumj** [pingcap/tidb#34435]
We’re scraping the `/metrics` of TiDB components (tikv, pd, tidb) outside of the TiDB monitor stack and found that we need to export the TLS items created by the operator to allow Prometheus to successfully scrape these components (otherwise the server rejects the request).

My understanding is that metrics run on a different port which should be safe to lower the security requirements. Is there a reason SSL verification is needed for Prometheus monitoring too?

**Comment by ljluestc** [comment]
```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tikv'
    static_configs:
      - targets: ['tikv.example.com:20180']  # Replace with actual TiKV address and port
    scheme: https                            # Use 'https' since you're dealing with SSL
    tls_config:
      ca_file: /path/to/tls/ca.crt           # Path to the CA certificate file
      cert_file: /path/to/tls/client.crt     # Path to the client certificate file
      key_file: /path/to/tls/client.key      # Path to the client private key file
    # Other scrape settings...

  - job_name: 'pd'
    static_configs:
      - targets: ['pd.example.com:2379']     # Replace with actual PD address and port
    scheme: https
    tls_config:
      ca_file: /path/to/tls/ca.crt
      cert_file: /path/to/tls/client.crt
      key_file: /path/to/tls/client.key
    # Other scrape settings...

  - job_name: 'tidb'
    static_configs:
      - targets: ['tidb.example.com:10080']  # Replace with actual TiDB address and port
    scheme: https
    tls_config:
      ca_file: /path/to/tls/ca.crt
      cert_file: /path/to/tls/client.crt
      key_file: /path/to/tls/client.key
    # Other scrape settings...
```
