### ISSUE TITLE
lightning: restoring dataset using auto-generated ID failed

### ISSUE THREAD

**Issue by buchuitoudegou** [pingcap/tidb#35338]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> create table test(id bigint unsigned auto_increment primary key, a int, b text, c text);
Query OK, 0 rows affected (0.10 sec)

mysql> alter table test auto_increment=9223372036854775802;
Query OK, 0 rows affected (0.11 sec)
```
```toml
[lightning]
# Logging
file = "/home/tidb-lightning1.log"
level = "debug"
check-requirements = false

[tikv-importer]
# Uses the Local-backend
backend = "local"
# Sets the directory for temporarily storing the sorted key-value pairs.
# The target directory must be empty.
# disk-quota = "500MB"
sorted-kv-dir = "/tmp/sst1"
incremental-import = true
```
data:
```csv
a,b,c
1,'a','b'
1,'a','b'
1,'a','b'
1,'a','b'
1,'a','b'
1,'a','b'
1,'a','b'
1,'a','b'
1,'a','b'
1,'a','b'
```

### 2. What did you expect to see? (Required)
1. restoring succeeded
```
mysql> insert into test(a,b,c) values(1,'a','b');
Query OK, 1 row affected (0.02 sec)

mysql> select * from test;
+---------------------+------+------+------+
| id                  | a    | b    | c    |
+---------------------+------+------+------+
| 9223372036854775802 |    1 | a    | b    |
+---------------------+------+------+------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
```
Verbose debug logs will be written to /home/tidb-lightning1.log

Error: [Lighting:Restore:ErrChecksumMismatch]checksum mismatched remote vs local => (checksum: 17991905197312659261 vs 4994735934893732502) (total_kvs: 7 vs 10) (total_bytes:287 vs 410)
tidb lightning encountered error: [Lighting:Restore:ErrChecksumMismatch]checksum mismatched remote vs local => (checksum: 17991905197312659261 vs 4994735934893732502) (total_kvs: 7 vs 10) (total_bytes:287 vs 410)
```

### 4. What is your TiDB version? (Required)
26df62fef2aaef130c4c3e821a5ba7f37c1eb4d1
