### ISSUE TITLE
Set `report-status = false` cause `auto_id_cache 1` not work

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#40697]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```toml
 [status]
 # If enable status report HTTP service.
report-status = false
```

```sql
create table t(a int auto_increment, key k(a)) auto_id_cache 1;
insert into t values ();
```

### 2. What did you expect to see? (Required)

insert success

### 3. What did you see instead (Required)

```sql
mysql> insert into t values ();
ERROR 1105 (HY000): autoid service leader not found
```

### 4. What is your TiDB version? (Required)

5cb64fd09a99335c4588195c52e4e91884da6451
