### ISSUE TITLE
lightning checksum report "Region is unavailable" and  tikv report "Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number"

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#45462]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- use below config to make it easier to reproduce
```toml
checksum-table-concurrency = 1
distsql-scan-concurrency = 5 # or even smaller
```
-  import 2 tables. checksum each table takes about 10m
- during checksum of second table will report error

related issue https://github.com/tikv/grpc-rs/issues/619

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
checksum failed
### 4. What is your TiDB version? (Required)
7.1.0/6.5.2
