### ISSUE TITLE
set `isolation-read` for each tidb instance can't work

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#48177]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a cluster with 2 tidb nodes, and set different `isolation-read.engines`
```yaml
  tidb_servers:
    - host: 127.0.0.1
      config:
        isolation-read.engines: ["tikv", "tidb"]
    - host: 127.0.0.1
      status_port: 10090
      port: 4001
      config:
        isolation-read.engines: ["tiflash", "tidb"]
```
2. check the  config and `tidb_isolation_read_engines` for each tidb instance

### 2. What did you expect to see? (Required)
1. config and tidb_isolation_read_engines correct
```sql
-- 4000 instance
mysql>  select @@tidb_isolation_read_engines;
+-------------------------------+
| @@tidb_isolation_read_engines |
+-------------------------------+
| tikv,tidb                  |
+-------------------------------+
-- 4001 instance
mysql>  select @@tidb_isolation_read_engines;
+-------------------------------+
| @@tidb_isolation_read_engines |
+-------------------------------+
| tiflash,tidb                  |
+-------------------------------+
```
### 3. What did you see instead (Required)
1. config shows ok
```sql
mysql> show config where name like '%isolation-read%';
+------+----------------+------------------------+--------------------+
| Type | Instance       | Name                   | Value              |
+------+----------------+------------------------+--------------------+
| tidb | 127.0.0.1:4000 | isolation-read.engines | ["tikv","tidb"]    |
| tidb | 127.0.0.1:4001 | isolation-read.engines | ["tiflash","tidb"] |
+------+----------------+------------------------+--------------------+
```
3. tidb_isolation_read_engines are same on every tidb instance 
```sql
-- 4000 instance
mysql>  select @@tidb_isolation_read_engines;
+-------------------------------+
| @@tidb_isolation_read_engines |
+-------------------------------+
| tiflash,tidb                  |
+-------------------------------+
-- 4001 instance
mysql>  select @@tidb_isolation_read_engines;
+-------------------------------+
| @@tidb_isolation_read_engines |
+-------------------------------+
| tiflash,tidb                  |
+-------------------------------+
```
### 4. What is your TiDB version? (Required)
`>=` 7.2.0 
master
