### ISSUE TITLE
config file: redundant names

### ISSUE THREAD

**Issue by andelf** [pingcap/tidb#4913]
```toml
[plan-cache]
plan-cache-enabled = false
plan-cache-capacity = 2560
plan-cache-shards = 256
```

and:

```toml
[prepared-plan-cache]
prepared-plan-cache-enabled = false
prepared-plan-cache-capacity = 100
```

Have common prefixes.

**Comment by shenli** [comment]
`plan-cache` and `prepared-plan-cache` are the same prefix?

**Comment by andelf** [comment]
should be:

```toml
[plan-cache]
enabled = false
capacity = 2560
shards = 256

[prepared-plan-cache]
enabled = false
capacity = 100
```
