### ISSUE TITLE
(pd-microservices) after enable pd microservice, "set global tidb_enable_tso_follower_proxy = 1" will be stuck

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tidb#51194]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

config tidb cluster as following.
```
    - name: tc
      type: TIDB_CLUSTER
      spec:
        pd:
          baseImage: hub-new.pingcap.net/qa/pd
          version: master
          config: |
            [dashboard]
            internal-proxy = true        
          limits:
            cpu: 500m
            memory: 1Gi
            storage: 1500Gi
          mode: ms
          replicas: 1
          requests:
            cpu: 151m
            memory: 600Mi
            storage: 1500Gi
          service:
            type: NodePort
        pdms:
          - baseImage: hub-new.pingcap.net/qa/pd
            config: |
              [log.file]
              filename = "/var/lib/pd/tso/tso.log"         
            limits:
              cpu: 2000m
              memory: 2Gi
              storage: 10Gi
            name: tso
            replicas: 2
            requests:
              cpu: 2000m
              memory: 2Gi
              storage: 10Gi
            storageVolumes:
              - mountPath: /var/lib/pd/tso
                name: log
                storageClassName: local-path
                storageSize: 10Gi
            version: master
          - baseImage: hub-new.pingcap.net/qa/pd
            config: |
              [log.file]
              filename = "/var/lib/pd/scheduling/scheduling.log"          
            limits:
              cpu: 2000m
              memory: 2Gi
              storage: 20Gi
            name: scheduling
            replicas: 2
            requests:
              cpu: 2000m
              memory: 2Gi
              storage: 20Gi
            storageVolumes:
              - mountPath: /var/lib/pd/scheduling
                name: log
                storageClassName: local-path
                storageSize: 20Gi
            version: master
```
run following set in sql
```
set global tidb_enable_tso_follower_proxy = 1
```

### 2. What did you expect to see? (Required)
Return failed.

### 3. What did you see instead (Required)
stuck more than 1 hours.

### 4. What is your TiDB version? (Required)
master
