### ISSUE TITLE
tidb config doesn't take effects when there are invalid config

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#51399]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. write config like
```
  global:
    user: "guojiangtao"
    ssh_port: 22
    deploy_dir: "/home/guojiangtao/work/tiup_cluster/s3/data/deploy"
    data_dir: "/home/guojiangtao/work/tiup_cluster/s3/data/data"
    arch: "amd64"

  server_configs:
    tidb:
      mem-quota-query: 1073741824
      log.file.max-backups: 10
      log.file.max-days: 5
      log.slow-threshold: 1000
      disaggregated-tiflash: true
      new_collations_enabled_on_first_bootstrap: false
      oom-action: log
      performance.enforce-mpp: 1
      performance.txn-total-size-limit: 107374182
...
```
2. tiup cluster setup new cluster
3. check `disaggregated-tiflash` config: `show config where name like '%disagg%'`

### 2. What did you expect to see? (Required)
tidb config is correct
### 3. What did you see instead (Required)
`disaggregated-tiflash` config is wrong
![ed8e4b65-0641-421e-b169-d883cd75ccd2](https://github.com/pingcap/tidb/assets/7493273/04ef5e82-d2f4-418b-b268-407c11e85e4d)

### 4. What is your TiDB version? (Required)
v7.5.0
