### ISSUE TITLE
subqueries produce different result between different deploy topology (3)

### ISSUE THREAD

**Issue by r33s3n6** [pingcap/tidb#52778]
### 1. Minimal reproduce step (Required)
First execute `init.sql` to create the table. Then executing `error.sql` yields unexpected results. Note that reproducing these results might not be entirely stable. Typically, it can be completed within three attempts. You can try executing multiple times or execute it again after rebuilding the table.
[init.sql.txt](https://github.com/pingcap/tidb/files/15047300/init.sql.txt)
[error.sql.txt](https://github.com/pingcap/tidb/files/15047299/error.sql.txt)

### 2. What did you expect to see? (Required)
The first column is a column `c_este10ce0x` in the table. 
The second column is a subquery that searches for the maximum value of `ref_2.c_este10ce0x between ref_5.c_ub_1s91wi and NULL`. If the maximum value of `ref_5.c_ub_1s91wi` is less than `c_este10ce0x`, all values will be evaluated as NULL, and thus output NULL. Otherwise, there exist some rows evaluated as 0, and thus output 0.

### 3. What did you see instead (Required)
In both TiDB multi-node and TiDB single-node versions, incorrect values are present, but the results are different.
Under the constraint condition, the maximum value of `ref_5.c_ub_1s91wi` is 2114215637. However, even when `c_este10ce0x` is less than this value, some result is still evaluated as NULL.
[output_re_main.log](https://github.com/pingcap/tidb/files/15047301/output_re_main.log)
[output_re_single.log](https://github.com/pingcap/tidb/files/15047302/output_re_single.log)

### 4. What is your TiDB version? (Required)
```
Release Version: v7.5.1
Edition: Community
Git Commit Hash: 7d16cc79e81bbf573124df3fd9351c26963f3e70
Git Branch: heads/refs/tags/v7.5.1
UTC Build Time: 2024-02-27 14:28:32
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```
topology:

distributed.yaml:
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

pd_servers:
  - host: 10.0.2.31

tidb_servers:
  - host: 10.0.2.21
  - host: 10.0.2.22

tikv_servers:
  - host: 10.0.2.11
  - host: 10.0.2.12
  - host: 10.0.2.13

monitoring_servers:
  - host: 10.0.2.8

grafana_servers:
  - host: 10.0.2.8

alertmanager_servers:
  - host: 10.0.2.8
```

single.yaml
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

pd_servers:
  - host: 10.0.2.73

tidb_servers:
  - host: 10.0.2.72

tikv_servers:
  - host: 10.0.2.71

```

### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in TiDB that may lead to database logic error.
