### ISSUE TITLE
subqueries produce different result between different deploy topology (2)

### ISSUE THREAD

**Issue by r33s3n6** [pingcap/tidb#52777]
### 1. Minimal reproduce step (Required)
First execute `init.sql` to create the table. Then executing `error.sql` yields unexpected results. Note that reproducing these results might not be entirely stable. Typically, it can be completed within three attempts. You can try executing multiple times or execute it again after rebuilding the table.
[init.sql.txt](https://github.com/pingcap/tidb/files/15046735/init.sql.txt)
[error.sql.txt](https://github.com/pingcap/tidb/files/15046734/error.sql.txt)

### 2. What did you expect to see? (Required)
The first column is a column c_k in the table. 
The second column is the maximum value of t_xf1at0.c_pv from another table t_xf1at0 under certain conditions. 
The third column is a subquery that calculates `t_xf1at0.c_pv <= c_k`, sorted in ascending order. If the maximum value of t_xf1at0.c_pv is greater than c_k, the result should be 0; otherwise, it should be 1.

### 3. What did you see instead (Required)
In both TiDB multi-node and TiDB single-node versions, incorrect values are present, but the results are different.
[output_re_main.log](https://github.com/pingcap/tidb/files/15046736/output_re_main.log)
[output_re_single.log](https://github.com/pingcap/tidb/files/15046737/output_re_single.log)

### 4. What is your TiDB version? (Required)
```
Release Version: v7.5.1
Edition: Community
Git Commit Hash: 7d16cc79e81bbf573124df3fd9351c26963f3e70
Git Branch: heads/refs/tags/v7.5.1
UTC Build Time: 2024-02-27 14:28:32
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```
topology:

distributed.yaml:
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

pd_servers:
  - host: 10.0.2.31

tidb_servers:
  - host: 10.0.2.21
  - host: 10.0.2.22

tikv_servers:
  - host: 10.0.2.11
  - host: 10.0.2.12
  - host: 10.0.2.13

monitoring_servers:
  - host: 10.0.2.8

grafana_servers:
  - host: 10.0.2.8

alertmanager_servers:
  - host: 10.0.2.8
```

single.yaml
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

pd_servers:
  - host: 10.0.2.73

tidb_servers:
  - host: 10.0.2.72

tikv_servers:
  - host: 10.0.2.71

```

### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in TiDB that may lead to database logic error.
