### ISSUE TITLE
unioned query with `var_pop` over window may lead to incorrect result

### ISSUE THREAD

**Issue by r33s3n6** [pingcap/tidb#52985]
### 1. Minimal reproduce step (Required)
Firstly, execute `init.sql` to create the table. Then executing `error.sql` yields unexpected results. Note that reproducing these results might not be entirely stable. Typically, it can be completed within three attempts. You can try executing `error.sql` multiple times or execute `init.sql` again to rebuild the table.

[init.sql.txt](https://github.com/pingcap/tidb/files/15147238/init.sql.txt)
[error.sql.txt](https://github.com/pingcap/tidb/files/15147237/error.sql.txt)

### 2. What did you expect to see? (Required)
The SQL statement consists of a UNION of two queries. The first query has four rows with the first column being respectively `oyz4u`, `wcnmm`, `z36ma`, and `tl`. The first column of the second query is a constant string '1'.

### 3. What did you see instead (Required)
In the multi-node version, some results other than '1' are outputted, while the single-node version behaves normally.

[output_re_main2.log](https://github.com/pingcap/tidb/files/15147239/output_re_main2.log)
[output_re_single2.log](https://github.com/pingcap/tidb/files/15147240/output_re_single2.log)

### 4. What is your TiDB version? (Required)
```
Release Version: v8.0.0
Edition: Community
Git Commit Hash: 8ba1fa452b1ccdbfb85879ea94b9254aabba2916
Git Branch: HEAD
UTC Build Time: 2024-03-28 14:22:15
GoVersion: go1.21.4
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```
topology:

distributed.yaml:
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

pd_servers:
  - host: 10.0.2.31

tidb_servers:
  - host: 10.0.2.21

tikv_servers:
  - host: 10.0.2.11
  - host: 10.0.2.12
  - host: 10.0.2.13

monitoring_servers:
  - host: 10.0.2.8

grafana_servers:
  - host: 10.0.2.8

alertmanager_servers:
  - host: 10.0.2.8

tiflash_servers:
  - host: 10.0.2.32
```

single.yaml
```
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/tidb-deploy"
  data_dir: "/tidb-data"

pd_servers:
  - host: 10.0.2.73

tidb_servers:
  - host: 10.0.2.72

tikv_servers:
  - host: 10.0.2.71

tiflash_servers:
  - host: 10.0.2.74
```

### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in TiDB that may lead to database logic error.
