### ISSUE TITLE
After configuring multi cn, tidb shows down

### ISSUE THREAD

**Issue by lhy1024** [pingcap/tidb#55372]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`tiup cluster tls test enable`
![image](https://github.com/user-attachments/assets/994b0fc8-481e-4e51-9712-7800c5f1c2c7)
edit config and add `cluster-verify-cn`

```
tidb_servers:
- host: 192.168.8.88
  ssh_port: 22
  port: 4000
  status_port: 10080
  deploy_dir: /tidb-deploy/tidb-4000
  log_dir: /tidb-deploy/tidb-4000/log
  config:
    security.cluster-ssl-ca: /tidb-deploy/tidb-4000/tls/ca.crt
    security.cluster-ssl-cert: /tidb-deploy/tidb-4000/tls/tidb.crt
    security.cluster-ssl-key: /tidb-deploy/tidb-4000/tls/tidb.pem
    security.cluster-verify-cn:
      - tidb
      - tikv
      - pd
  arch: amd64
  os: linux
tikv_servers:
- host: 192.168.8.88
  ssh_port: 22
  port: 20160
  status_port: 20180
  deploy_dir: /data1/tidb-deploy/tikv-20160
  data_dir: /data1/tidb-data/tikv-20160
  log_dir: /data1/tidb-deploy/tikv-20160/log
  config:
    security.ca-path: /data1/tidb-deploy/tikv-20160/tls/ca.crt
    security.cert-allowed-cn:
      - tidb
      - tikv
      - pd
    security.cert-path: /data1/tidb-deploy/tikv-20160/tls/tikv.crt
    security.key-path: /data1/tidb-deploy/tikv-20160/tls/tikv.pem
  arch: amd64
  os: linux
tiflash_servers: []
pd_servers:
- host: 192.168.8.88
  ssh_port: 22
  patched: true
  name: pd-192.168.8.88-2379
  client_port: 2379
  peer_port: 2380
  deploy_dir: /tidb-deploy/pd-2379
  data_dir: /tidb-data/pd-2379
  log_dir: /tidb-deploy/pd-2379/log
  config:
    security.cacert-path: /tidb-deploy/pd-2379/tls/ca.crt
    security.cert-path: /tidb-deploy/pd-2379/tls/pd.crt
    security.cluster-verify-cn:
      - tidb
      - tikv
      - pd
    security.key-path: /tidb-deploy/pd-2379/tls/pd.pem
  arch: amd64
  os: linux
```

### 2. What did you expect to see? (Required)
work normal

### 3. What did you see instead (Required)
![image](https://github.com/user-attachments/assets/c6add6fd-c8cf-463f-b637-9876fddc5819)
![image](https://github.com/user-attachments/assets/2428f76f-958c-4d55-aa6d-cb126d963550)
