### ISSUE TITLE
ingress-nginx to expose can not expose tidb dashboard

### ISSUE THREAD

**Issue by JacksonChen63** [pingcap/tidb#56854]
Accroding this configuration, still not worked, we got 504 gateway timeout.

ref: https://asktug.com/t/topic/1011985

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lqb-yz-dashboard
  namespace: tidb
spec:
  rules:
    - host: "lqb.mytest.org"
      http:
        paths:
        - path: "/dashboard"
          pathType: Prefix
          backend:
            service:
              name: lqb-discovery
              port:
                number: 10262
```

I also have refer this page, but still not worked for me

ref: https://docs.pingcap.com/tidb-in-kubernetes/stable/access-dashboard

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: access-dashboard
  namespace: ${namespace}
spec:
  rules:
    - host: ${host}
      http:
        paths:
          - backend:
              serviceName: ${SERVICE_NAME}
              servicePort: ${PORT}
            path: ${HTTP_PATH}
```

 Is there have any idea?
