### ISSUE TITLE
Cannot run tiup playground

### ISSUE THREAD

**Issue by duerwuyi** [pingcap/tidb#58065]
### 1. Minimal reproduce step (Required)

curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh 
 tiup playground v8.4.0 --host 0.0.0.0 --tag=devenv --db 1 --kv 1 --pd 1 --tiflash 0

### 2. What did you expect to see? (Required)
cluster started

### 3. What did you see instead (Required)

![Image](https://github.com/user-attachments/assets/4b934ead-2032-42bb-b508-55f2e88ca8dc)

### 4. What is your TiDB version? (Required)

v8.4.0 and v8.5.0(nightly) could both trigger the same bug, but v8.1.0 won't. It was reproduced on three different computers. All of them have the OS of Ubuntu 22.04 and 16GB RAM.

**Comment by lance6716** [comment]
firs error is tikv "illegal instruction". What's your CPU architecture?

**Comment by Defined2014** [comment]
Please provide the result of `cat /proc/cpuinfo`

**Comment by duerwuyi** [comment]
In this picture, cpu is: Intel(R) Xeon(R) CPU  E5530
I also tried to run tikv in my personal computer using docker desktop for windows, the cpu is AMD 3700X, and the tikv quitted unexpectedly too. I am more eager to solve the question on this problem.
```
# Dockerfile:
FROM rockylinux:9.3.20231119

ARG TIDB_VERSION=v8.4.0

VOLUME /tidb-data

RUN dnf -y update && dnf -y install glibc-langpack-en procps-ng psmisc \
  && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh \
  && /root/.tiup/bin/tiup install pd:${TIDB_VERSION} tidb:${TIDB_VERSION} tiflash:${TIDB_VERSION} tikv:${TIDB_VERSION} prometheus:${TIDB_VERSION} \
  && mkdir -p /root/.tiup/data \
  && ln -sf /tidb-data /root/.tiup/data/devenv

ENV PATH=/root/.tiup/bin:$PATH \
  LANG="en_US.UTF-8" \
  LANGUAGE="en_US:en" \
  LC_ALL="en_US.UTF-8" \
  TZ="Asia/Shanghai"

EXPOSE 2379 3000 4000 9090 10080
```
and
```
# Docker-Compose.yml
version: "3"
services:
  tidb1:
    build:
      context: .
      dockerfile: Dockerfile.tidb
    command: /bin/sh -c "exec /root/.tiup/bin/tiup playground ${TIDB_VERSION} --host 0.0.0.0 --tag=devenv --db 1 --kv 1 --pd 1 --tiflash 0"
    ports:
      - "4000:4000"   # tidb(mysql protocol)
      - "10080:10080" # tidb(http protocol)
      - "2379:2379"   # pd/dashboard
      - "3000:3000"   # grafana
  tidb2:
    build:
      context: .
      dockerfile: Dockerfile.tidb
    command: /bin/sh -c "exec /root/.tiup/bin/tiup playground ${TIDB_VERSION} --host 0.0.0.0 --tag=devenv --db 1 --kv 3 --pd 1 --tiflash 0"
    ports:
      - "4001:4000"   # tidb(mysql protocol)
      - "10081:10080" # tidb(http protocol)
      - "2378:2379"   # pd/dashboard
      - "3001:3000"   # grafana
```
I found that "tidb2" is very memory-and-CPU-consuming, and once started, tikv will quit.
