### ISSUE TITLE
The Lightning table creation is getting slower and slower

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#58649]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

A lighting import 1 million tables(10k rows per table)
![Image](https://github.com/user-attachments/assets/80a969e7-7ee4-4a9c-bdfe-c539a9d61922)
![Image](https://github.com/user-attachments/assets/aff2a988-7a29-48b7-918f-86b975477f2b)
![Image](https://github.com/user-attachments/assets/069ad316-dcb1-4fe8-9dce-6b42eeaf252e)

```toml
### tidb-lightning configuration
[lightning]
# check if the cluster satisfies the minimum requirement before starting
check-requirements = false
index-concurrency = 16
table-concurrency = 16

[mydumper]
no-schema = true
case-sensitive = false
data-source-dir = "/data/dumpling"

# https://docs.pingcap.com/zh/tidb/stable/tidb-lightning-configuration
[conflict]
strategy = ""

[tikv-importer]
backend = "local"
sorted-kv-dir = "/data/sorted-kv-dir"
# parallel-import = true
disk-quota = "1TB"
range-concurrency = 4
pause-pd-scheduler-scope = "global"

# CSV files are imported according to MySQL LOAD DATA INFILE rules.
[mydumper.csv]
# separator between fields, should be an ASCII character.
separator = ","
# whether the CSV files contain a header. If true, the first line will be skipped
header = true
# whether the CSV contains any NULL value. If true, all columns from CSV cannot be NULL.
not-null = false
# if non-null = false (i.e. CSV can contain NULL), fields equal to this value will be treated as NULL
null = "NULL"
# whether to interpret backslash-escape inside strings.
backslash-escape = false
# if a line ends with a separator, remove it.
trim-last-separator = false

[checkpoint]
enable = true

# post-restore provide some options which will be executed after all kv data has been imported into the tikv cluster.
# the execution order are(if set true): checksum -> analyze
[post-restore]
# if set true, checksum will do ADMIN CHECKSUM TABLE <table> for each table.
# checksum = false
# if set true, analyze will do ANALYZE TABLE <table> for each table.
analyze = false

[tidb]
checksum-table-concurrency = 16
```
### 4. What is your TiDB version? (Required)

Release Version: v9.0.0-alpha-26-g284a3ee23c
Git Commit Hash: 284a3ee23c7ae200e2d9579129361997d6465acb
Git Branch: HEAD
Go Version: go1.23.4
UTC Build Time: 2024-12-31 07:12:03
Race Enabled: false
