### ISSUE TITLE
Wrong column content in INFORMATION_SCHEMA.TIDB_SERVERS_INFO

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#59245]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

start a TiDB with

```toml
labels = { zone = "us-west-1", dc = "dc1", rack = "rack1", host = "tidb1" }
```

### 2. What did you expect to see? (Required)

```
mysql> select * from INFORMATION_SCHEMA.TIDB_SERVERS_INFO\G
*************************** 1. row ***************************
       DDL_ID: f6c64fdc-d4fe-4268-bbcc-fea3fcf46054
           IP: 2408:8207:1857:3610:4a5:de9e:e383:2cfb
         PORT: 4000
  STATUS_PORT: 10080
        LEASE: 45s
      VERSION: 8.0.11-TiDB-v9.0.0-alpha-197-g43f2fb91d7
     GIT_HASH: 43f2fb91d740aaf45774d99b71554eead12009cc
       LABELS: dc=dc1,host=tidb1,rack=rack1,zone=us-west-1
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from INFORMATION_SCHEMA.TIDB_SERVERS_INFO\G
*************************** 1. row ***************************
       DDL_ID: f6c64fdc-d4fe-4268-bbcc-fea3fcf46054
           IP: 2408:8207:1857:3610:4a5:de9e:e383:2cfb
         PORT: 4000
  STATUS_PORT: 10080
        LEASE: 45s
      VERSION: 8.0.11-TiDB-v9.0.0-alpha-197-g43f2fb91d7
     GIT_HASH: 43f2fb91d740aaf45774d99b71554eead12009cc
BINLOG_STATUS: dc=dc1,host=tidb1,rack=rack1,zone=us-west-1
       LABELS:
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master
