### ISSUE TITLE
No information of all regions in SHOW TABLE table_name REGIONS\G output

### ISSUE THREAD

**Issue by ankiteric** [pingcap/tidb#61248]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> CREATE TABLE t_part_hash (     id BIGINT PRIMARY KEY AUTO_RANDOM,     insert_seq BIGINT AUTO_INCREMENT,     UNIQUE INDEX idx_insert_seq (id,insert_seq)  )
PARTITION BY HASH(id) PARTITIONS 8;
Query OK, 0 rows affected, 1 warning (0.55 sec)

mysql> INSERT INTO t_part_hash (insert_seq)
    -> WITH RECURSIVE seq AS (
    ->     SELECT 1 AS n
    ->     UNION ALL
    ->     SELECT n + 1 FROM seq WHERE n < 10000
    -> )
    -> SELECT NULL FROM seq;
Query OK, 10000 rows affected (0.21 sec)



mysql> SHOW TABLE t_part_hash REGIONS\G
*************************** 1. row ***************************
             REGION_ID: 75991496460
             START_KEY: t_7358_
               END_KEY: t_7359_
             LEADER_ID: 75991496462
       LEADER_STORE_ID: 6
                 PEERS: 75991496461, 75991496462, 75991496463
            SCATTERING: 0
         WRITTEN_BYTES: 583530
            READ_BYTES: 92033
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 2. row ***************************
             REGION_ID: 75991496700
             START_KEY: t_7359_
               END_KEY: t_7360_
             LEADER_ID: 75991496702
       LEADER_STORE_ID: 6
                 PEERS: 75991496701, 75991496702, 75991496703
            SCATTERING: 0
         WRITTEN_BYTES: 583588
            READ_BYTES: 91250
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 3. row ***************************
             REGION_ID: 75991497006
             START_KEY: t_7360_
               END_KEY: t_7361_
             LEADER_ID: 75991497008
       LEADER_STORE_ID: 6
                 PEERS: 75991497007, 75991497008, 75991497009
            SCATTERING: 0
         WRITTEN_BYTES: 583546
            READ_BYTES: 91250
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 4. row ***************************
             REGION_ID: 75991497141
             START_KEY: t_7361_
               END_KEY: t_7362_
             LEADER_ID: 75991497143
       LEADER_STORE_ID: 6
                 PEERS: 75991497142, 75991497143, 75991497144
            SCATTERING: 0
         WRITTEN_BYTES: 583573
            READ_BYTES: 91250
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 5. row ***************************
             REGION_ID: 75991497471
             START_KEY: t_7362_
               END_KEY: t_7363_
             LEADER_ID: 75991497473
       LEADER_STORE_ID: 6
                 PEERS: 75991497472, 75991497473, 75991497474
            SCATTERING: 0
         WRITTEN_BYTES: 583576
            READ_BYTES: 91250
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 6. row ***************************
             REGION_ID: 75991497801
             START_KEY: t_7363_
               END_KEY: t_7364_
             LEADER_ID: 75991497803
       LEADER_STORE_ID: 6
                 PEERS: 75991497802, 75991497803, 75991497804
            SCATTERING: 0
         WRITTEN_BYTES: 583609
            READ_BYTES: 91250
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 7. row ***************************
             REGION_ID: 75991498003
             START_KEY: t_7364_
               END_KEY: t_7365_
             LEADER_ID: 75991498005
       LEADER_STORE_ID: 6
                 PEERS: 75991498004, 75991498005, 75991498006
            SCATTERING: 0
         WRITTEN_BYTES: 583531
            READ_BYTES: 91250
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 8. row ***************************
             REGION_ID: 24481069
             START_KEY: t_7365_
               END_KEY: 78000000
             LEADER_ID: 24481071
       LEADER_STORE_ID: 6
                 PEERS: 24481070, 24481071, 24481104
            SCATTERING: 0
         WRITTEN_BYTES: 583708
            READ_BYTES: 374201
  APPROXIMATE_SIZE(MB): 38
      APPROXIMATE_KEYS: 25790
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
8 rows in set (0.03 sec)
```


No  information in all regions except last one. Lets try to insert some more records

```
mysql> INSERT INTO t_part_hash (insert_seq) WITH RECURSIVE seq AS (     SELECT 1 AS n     UNION ALL     SELECT n + 1 FROM seq WHERE n < 300000 ) SELECT NULL FROM
seq;
Query OK, 300000 rows affected (4.67 sec)
Records: 300000  Duplicates: 0  Warnings: 0

mysql> INSERT INTO t_part_hash (insert_seq) WITH RECURSIVE seq AS (     SELECT 1 AS n     UNION ALL     SELECT n + 1 FROM seq WHERE n < 300000 ) SELECT NULL FROM
seq;
Query OK, 300000 rows affected (5.11 sec)
Records: 300000  Duplicates: 0  Warnings: 0

mysql> INSERT INTO t_part_hash (insert_seq) WITH RECURSIVE seq AS (     SELECT 1 AS n     UNION ALL     SELECT n + 1 FROM seq WHERE n < 300000 ) SELECT NULL FROM
seq;
Query OK, 300000 rows affected (5.61 sec)
Records: 300000  Duplicates: 0  Warnings: 0

mysql> INSERT INTO t_part_hash (insert_seq) WITH RECURSIVE seq AS (     SELECT 1 AS n     UNION ALL     SELECT n + 1 FROM seq WHERE n < 300000 ) SELECT NULL FROM
seq;
Query OK, 300000 rows affected (5.39 sec)
Records: 300000  Duplicates: 0  Warnings: 0

mysql> INSERT INTO t_part_hash (insert_seq) WITH RECURSIVE seq AS (     SELECT 1 AS n     UNION ALL     SELECT n + 1 FROM seq WHERE n < 300000 ) SELECT NULL FROM
seq;
Query OK, 300000 rows affected (6.10 sec)
Records: 300000  Duplicates: 0  Warnings: 0

mysql> INSERT INTO t_part_hash (insert_seq) WITH RECURSIVE seq AS (     SELECT 1 AS n     UNION ALL     SELECT n + 1 FROM seq WHERE n < 300000 ) SELECT NULL FROM
seq;
Query OK, 300000 rows affected (4.98 sec)
Records: 300000  Duplicates: 0  Warnings: 0
```

Lets again check the region status of this table


```
mysql> SHOW TABLE t_part_hash REGIONS\G;
*************************** 1. row ***************************
             REGION_ID: 75991496460
             START_KEY: t_7358_
               END_KEY: t_7359_
             LEADER_ID: 75991496462
       LEADER_STORE_ID: 6
                 PEERS: 75991496461, 75991496462, 75991496463
            SCATTERING: 0
         WRITTEN_BYTES: 0
            READ_BYTES: 2828750
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 2. row ***************************
             REGION_ID: 75991496700
             START_KEY: t_7359_
               END_KEY: t_7360_
             LEADER_ID: 75991496702
       LEADER_STORE_ID: 6
                 PEERS: 75991496701, 75991496702, 75991496703
            SCATTERING: 0
         WRITTEN_BYTES: 0
            READ_BYTES: 2828750
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 3. row ***************************
             REGION_ID: 75991497006
             START_KEY: t_7360_
               END_KEY: t_7361_
             LEADER_ID: 75991497008
       LEADER_STORE_ID: 6
                 PEERS: 75991497007, 75991497008, 75991497009
            SCATTERING: 0
         WRITTEN_BYTES: 0
            READ_BYTES: 2828750
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 4. row ***************************
             REGION_ID: 75991497141
             START_KEY: t_7361_
               END_KEY: t_7362_
             LEADER_ID: 75991497143
       LEADER_STORE_ID: 6
                 PEERS: 75991497142, 75991497143, 75991497144
            SCATTERING: 0
         WRITTEN_BYTES: 0
            READ_BYTES: 2828750
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 5. row ***************************
             REGION_ID: 75991497471
             START_KEY: t_7362_
               END_KEY: t_7363_
             LEADER_ID: 75991497473
       LEADER_STORE_ID: 6
                 PEERS: 75991497472, 75991497473, 75991497474
            SCATTERING: 0
         WRITTEN_BYTES: 0
            READ_BYTES: 2828750
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 6. row ***************************
             REGION_ID: 75991497801
             START_KEY: t_7363_
               END_KEY: t_7364_
             LEADER_ID: 75991497803
       LEADER_STORE_ID: 6
                 PEERS: 75991497802, 75991497803, 75991497804
            SCATTERING: 0
         WRITTEN_BYTES: 0
            READ_BYTES: 2828750
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 7. row ***************************
             REGION_ID: 75991498003
             START_KEY: t_7364_
               END_KEY: t_7365_
             LEADER_ID: 75991498005
       LEADER_STORE_ID: 6
                 PEERS: 75991498004, 75991498005, 75991498006
            SCATTERING: 0
         WRITTEN_BYTES: 0
            READ_BYTES: 2828750
  APPROXIMATE_SIZE(MB): 1
      APPROXIMATE_KEYS: 0
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
*************************** 8. row ***************************
             REGION_ID: 24481069
             START_KEY: t_7365_
               END_KEY: 78000000
             LEADER_ID: 24481071
       LEADER_STORE_ID: 6
                 PEERS: 24481070, 24481071, 24481104
            SCATTERING: 0
         WRITTEN_BYTES: 88689606
            READ_BYTES: 366300
  APPROXIMATE_SIZE(MB): 80
      APPROXIMATE_KEYS: 480922
SCHEDULING_CONSTRAINTS: 
      SCHEDULING_STATE: 
8 rows in set (0.06 sec)
```

No records in other regions. Lets check if other partition has some data


```
mysql> select count(1) from t_part_hash partition(p0);
+----------+
| count(1) |
+----------+
|   263750 |
+----------+
1 row in set (0.09 sec)

mysql> select count(1) from t_part_hash partition(p1);
+----------+
| count(1) |
+----------+
|   263750 |
+----------+
1 row in set (0.09 sec)

mysql> select count(1) from t_part_hash partition(p3);
+----------+
| count(1) |
+----------+
|   263750 |
+----------+
```




### 2. What did you expect to see? (Required)

Data about all regions

### 3. What did you see instead (Required)

Information only about one region and rest is empty inspite of having data in it.

### 4. What is your TiDB version? (Required)

mysql> SELECT tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v8.5.1
Edition: Community
Git Commit Hash: fea86c8e35ad4a86a5e1160701f99493c2ee547c
Git Branch: HEAD
UTC Build Time: 2025-01-16 07:38:34
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
