### ISSUE TITLE
TIFLASH port of 3930 cannot start，tiflash_tikv.log   Permission denied  TIUP DEPLOY failed

### ISSUE THREAD

**Issue by rola0411** [pingcap/tidb#62013]
## Bug Report
TIFLASH  tiflash_stderr.log error message
```
Logging information to /opt/deploy/tiflash-9000/log/tiflash.log
Logging errors to /opt/deploy/tiflash-9000/log/tiflash_error.log
deprecated configuration, log-file has been moved to log.file.filename
override log.file.filename with log-file, "/opt/deploy/tiflash-9000/log/tiflash_tikv.log"
failed to create engine log dir: Permission denied (os error 13)
```
**tiup`s the yaml** 
```
tiflash_servers:
  # # The ip address of the TiFlash Server.
  - host: 192.168.2.160
    # # SSH port of the server.
    # ssh_port: 22
    # # TiFlash TCP Service port.
    # # Since 7.1.0, it is not actually listened, and only being used as part of the instance identity.
    # tcp_port: 9000
    # # TiFlash raft service and coprocessor service listening address.
    # flash_service_port: 3930
    # # TiFlash Proxy service port.
    # flash_proxy_port: 20170
    # # TiFlash Proxy metrics port.
    # flash_proxy_status_port: 20292
    # # TiFlash metrics port.
    # metrics_port: 8234
    # # TiFlash Server deployment file, startup script, configuration file storage directory.
    # deploy_dir: /tidb-deploy/tiflash-9000
    ## With cluster version >= v4.0.9 and you want to deploy a multi-disk TiFlash node, it is recommended to
    ## check config.storage.* for details. The data_dir will be ignored if you defined those configurations.
    ## Setting data_dir to a ','-joined string is still supported but deprecated.
    ## Check https://docs.pingcap.com/tidb/stable/tiflash-configuration#multi-disk-deployment for more details.
    # # TiFlash Server data storage directory.
    # data_dir: /tidb-data/tiflash-9000
    # # TiFlash Server log file storage directory.
    log_dir: "/opt/logs"
  # # The ip address of the TiKV Server.
    config:
      logger.level: "info"
      storage.main.dir: [ "/opt/tidb/data_vdb", "/opt/tidb/data_vdc" ]
    #   ## Multi-disk deployment introduced in v4.0.9
    #   ## Check https://docs.pingcap.com/tidb/stable/tiflash-configuration#multi-disk-deployment for more details.
    #   ## Example1:
    
  - host: 192.168.2.161
    # ssh_port: 22
    # tcp_port: 9000
    # flash_service_port: 3930
    # flash_proxy_port: 20170
    # flash_proxy_status_port: 20292
    # metrics_port: 8234
    # deploy_dir: /tidb-deploy/tiflash-9000
    # # TiFlash Server log file storage directory.
    log_dir: "/opt/logs"
    config:
      logger.level: "info"
      storage.main.dir: [ "/opt/tidb/data_vdb", "/opt/tidb/data_vdc" ]
# # Server configs are used to specify the configuration of Prometheus Server.

```
and 

The 3930 port of tiflash cannot start, and there are no error logs for tiflash.
