### ISSUE TITLE
INFORMATION_SCHEMA.COLUMNS's PRECISION value for different type

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#7396]
1. What did you do?

```
create table testprec(x decimal, y time, z datetime, e timestamp, f bit);
select * from INFORMATION_SCHEMA.COLUMNS where TABLE_NAMe = 'testprec'\G;
```

2. What did you expect to see?

```
*************************** 1. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: x
       NUMERIC_PRECISION: 10
      DATETIME_PRECISION: NULL
   GENERATION_EXPRESSION: 
*************************** 2. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: y
       NUMERIC_PRECISION: NULL
      DATETIME_PRECISION: 0
   GENERATION_EXPRESSION: 
*************************** 3. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: z
       NUMERIC_PRECISION: NULL
      DATETIME_PRECISION: 0
   GENERATION_EXPRESSION: 
*************************** 4. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: e
       NUMERIC_PRECISION: NULL
      DATETIME_PRECISION: 0
   GENERATION_EXPRESSION: 
*************************** 5. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: f
       NUMERIC_PRECISION: 1
      DATETIME_PRECISION: NULL
   GENERATION_EXPRESSION: 
5 rows in set (0.00 sec)

```

3. What did you see instead?

```
*************************** 1. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
       NUMERIC_PRECISION: 0
      DATETIME_PRECISION: 0
   GENERATION_EXPRESSION: 
*************************** 2. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: y
       NUMERIC_PRECISION: 0
      DATETIME_PRECISION: 0
   GENERATION_EXPRESSION: 
*************************** 3. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: z
       NUMERIC_PRECISION: 0
      DATETIME_PRECISION: 0
      CHARACTER_SET_NAME: NULL
   GENERATION_EXPRESSION: 
*************************** 4. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: e
       NUMERIC_PRECISION: 0
      DATETIME_PRECISION: 0
   GENERATION_EXPRESSION: 
*************************** 5. row ***************************
           TABLE_CATALOG: def
            TABLE_SCHEMA: test
              TABLE_NAME: testprec
             COLUMN_NAME: f
       NUMERIC_PRECISION: 0
      DATETIME_PRECISION: 0
   GENERATION_EXPRESSION: 
5 rows in set (0.03 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
