### ISSUE TITLE
Specify the database name when sync to TiDB

### ISSUE THREAD

**Issue by leshalv** [pingcap/tidb#9687]
我有很多数据库，但是名称都一样，我想把它们全部同步到TiDB，我想问我如何在导入TiDB的时候指定库名？

**Comment by lamxTyler** [comment]
Thanks for your feedback! PTAL @amyangfei

**Comment by amyangfei** [comment]
@leshalv do you mean route multiple DB instances with the same schema name to different schema name in downstream? If so, you can start multiple syncers, and configure the `route-rules` to them, for example

```toml
[[route-rules]]
pattern-schema = "schema"
target-schema = "schema_1"

[from]
host = "10.0.2.10"
user = "root"
password = ""
port = 3306

[to]
host = "127.0.0.1"
user = "root"
password = ""
port = 4000
```

```toml
[[route-rules]]
pattern-schema = "schema"
target-schema = "schema_2"

[from]
host = "10.0.2.11"
user = "root"
password = ""
port = 3306

[to]
host = "127.0.0.1"
user = "root"
password = ""
port = 4000
```
