### ISSUE TITLE
syncer 使用 Prometheus ，当一个syncer 异常退出后，并没有触动Alerts

### ISSUE THREAD

**Issue by leshalv** [pingcap/tidb#9749]
![image](https://user-images.githubusercontent.com/30397655/54416123-65e93100-4739-11e9-9bf0-9fed21a9f834.png)
![image](https://user-images.githubusercontent.com/30397655/54416189-a9dc3600-4739-11e9-8bb3-753a3b3fa2c2.png)

**Comment by eurekaka** [comment]
@GregoryIan PTAL

**Comment by leshalv** [comment]
还没结果吗？

**Comment by GregoryIan** [comment]
I have no idea, you need a syncer process monitoring, @liubo0127 does prometheus provide this feature?

**Comment by leshalv** [comment]
你们有文档说提供了prometheus监控功能，但是那是prometheus 1X的，目前是2x ，不支持那种方式了，我改成了yml，无效，你们的文档地址：https://github.com/pingcap/docs-cn/blob/master/tools/syncer.md#%E9%85%8D%E7%BD%AE%20Syncer%20%E7%9B%91%E6%8E%A7%E4%B8%8E%E5%91%8A%E8%AD%A6

**Comment by GregoryIan** [comment]
The document only describe the Internal monitoring metrics of `Syncer`, I think you need a process monitoring, our DBA @superlzs0476 would help you

**Comment by superlzs0476** [comment]
Please upload the configuration yaml,I will test it on mine environment.

**Comment by leshalv** [comment]
groups:
  - name: alert.rules
    rules:
      - alert: syncer_status
        expr: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1
        for: 1m
        labels:
          env: hospital-sync
          channels: alerts
        annotations:
          description: "alert: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1 instance: {{     $labels.instance }} values: {{ $value }} "
          summary: syncer status error

**Comment by leshalv** [comment]
@superlzs0476 我重新改了下yaml，你看看，到底是哪里的问题呢？

**Comment by superlzs0476** [comment]
`groups:
  - name: alert.rules
    rules:
      - alert: syncer_status
        expr: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1
        for: 1m
        labels:
          env: hospital-sync
          channels: alerts
        annotations:
          description: "alert: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1, instance: {{ $labels.instance }}, values: {{ $value }} "
          values: '{{ $values }}'
          summary: syncer status error`

**Comment by superlzs0476** [comment]
groups:
  - name: alert.rules
    rules:
      - alert: syncer_status
        expr: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1
        for: 1m
        labels:
          env: hospital-sync
          channels: alerts
        annotations:
          description: "alert: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1, instance: {{ $labels.instance }}, values: {{ $value }} "
          values: '{{ $values }}'
          summary: syncer status error

**Comment by superlzs0476** [comment]
```yaml
groups:
  - name: alert.rules
    rules:
      - alert: syncer_status
        expr: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1
        for: 1m
        labels:
          env: hospital-sync
          channels: alerts
        annotations:
          description: "alert: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1 instance: {{     $labels.instance }} values: {{ $value }} "
          summary: syncer status error
```

**Comment by superlzs0476** [comment]
```yaml
groups:
  - name: alert.rules
    rules:
    - alert: syncer_status
      expr: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1
      for: 1m
      labels:
          env: hospital-sync
          channels: alerts
      annotations:
          description: "alert: syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1, instance: {{$labels.instance }}, values: {{ $value }}"
          value: '{{ $value }}'
          summary: syncer status error
```
I try to change syntax, please take a look.
